/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTranscripts"];
        put?: never;
        post: operations["CreateTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcripts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTranscript"];
        put: operations["UpdateTranscript"];
        post?: never;
        delete: operations["DeleteTranscript"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slide-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTemplates"];
        put?: never;
        post: operations["CreateTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slide-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTemplate"];
        put: operations["UpdateTemplate"];
        post?: never;
        delete: operations["DeleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Login with Firebase token.
         *     Verifies the token and returns user information.
         *     Creates a new user if one doesn't exist with the given Firebase UID.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get current user information.
         *     Requires authentication.
         */
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/desktop-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Generate a Firebase Custom Token for the authenticated user.
         *     Called by the web app after the user logs in, to hand off auth to the Electron desktop recorder.
         */
        get: operations["GetDesktopToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/presentations/{presentationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get a presentation for public viewing.
         *     No authentication required.
         */
        get: operations["GetPublicPresentation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListSessions"];
        put?: never;
        post: operations["CreateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/transcripts/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UploadTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/transcripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjectTranscripts"];
        put?: never;
        post: operations["CreateProjectTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/transcripts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportProjectTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/transcripts/{transcriptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProjectTranscript"];
        put: operations["UpdateProjectTranscript"];
        post?: never;
        delete: operations["DeleteProjectTranscript"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/transcripts/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateManualTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTasks"];
        put?: never;
        post: operations["CreateTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTask"];
        put: operations["UpdateTask"];
        post?: never;
        delete: operations["DeleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSession"];
        put: operations["UpdateSession"];
        post?: never;
        delete: operations["DeleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presentations/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GeneratePresentation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presentations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListPresentations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presentations/{presentationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPresentation"];
        put?: never;
        post?: never;
        delete: operations["DeletePresentation"];
        options?: never;
        head?: never;
        patch: operations["UpdatePresentation"];
        trace?: never;
    };
    "/api/presentations/{presentationId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdatePresentationStatus"];
        trace?: never;
    };
    "/api/jira/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAuthorizationUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jira/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HandleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/integrations/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIntegration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthcheck/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get Status. */
        get: operations["GetStatusPayload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListContexts"];
        put?: never;
        post: operations["CreateContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contexts/{contextId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContext"];
        put: operations["UpdateContext"];
        post?: never;
        delete: operations["DeleteContext"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contexts/{contextId}/files/{fileId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContextFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contexts/{contextId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UploadContextFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contexts/{contextId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeleteContextFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListThreads"];
        put?: never;
        post: operations["CreateThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetThread"];
        put: operations["UpdateThread"];
        post?: never;
        delete: operations["DeleteThread"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audio/transcribe-chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Transcribe a raw audio chunk uploaded by the Electron recorder.
         *     The Groq API key lives exclusively on the server — it is never sent to the client.
         */
        post: operations["TranscribeChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCustomTheme"];
        put: operations["UpsertCustomTheme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Delete a user account and all associated data (Admin only)
         *     This is a careful operation that deletes all related records to avoid foreign key constraint errors
         *     Only admins can delete other users
         */
        delete: operations["DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Delete your own user account and all associated data
         *     This endpoint allows users to delete their own account without specifying a userId
         *     The user ID is extracted from the authentication token
         */
        delete: operations["DeleteMyAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "_36_Enums.TranscriptSource": "MANUAL" | "RECORDING" | "UPLOAD" | "IMPORTED";
        TranscriptSource: components["schemas"]["_36_Enums.TranscriptSource"];
        /**
         * @description From https://github.com/sindresorhus/type-fest/
         *     Matches any valid JSON value.
         */
        JsonValue: (string | number | boolean | components["schemas"]["JsonObject"] | components["schemas"]["JsonArray"]) | null;
        /**
         * @description From https://github.com/sindresorhus/type-fest/
         *     Matches a JSON object.
         *     This type can be useful to enforce some input to be JSON-compatible or as a super-type to be extended from.
         */
        JsonObject: {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /**
         * @description From https://github.com/sindresorhus/type-fest/
         *     Matches a JSON array.
         */
        JsonArray: Record<string, never>;
        StandaloneTranscriptResponse: {
            id: string;
            projectId: string | null;
            userId: string;
            title: string | null;
            source: components["schemas"]["TranscriptSource"];
            language: string | null;
            summary: string | null;
            transcript: string | null;
            /** Format: date-time */
            recordedAt: string | null;
            metadata: components["schemas"]["JsonValue"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StandaloneTranscriptListResponse: {
            transcripts: components["schemas"]["StandaloneTranscriptResponse"][];
            /** Format: double */
            total: number;
        };
        ApiResponse_StandaloneTranscriptListResponse_: {
            message?: string;
            data: components["schemas"]["StandaloneTranscriptListResponse"] | null;
            /** Format: double */
            status: number;
        };
        ApiResponse_StandaloneTranscriptResponse_: {
            message?: string;
            data: components["schemas"]["StandaloneTranscriptResponse"] | null;
            /** Format: double */
            status: number;
        };
        /**
         * @description Matches any valid value that can be used as an input for operations like
         *     create and update as the value of a JSON field. Unlike \`JsonValue\`, this
         *     type allows read-only arrays and read-only object properties and disallows
         *     \`null\` at the top level.
         *
         *     \`null\` cannot be used as the value of a JSON field because its meaning
         *     would be ambiguous. Use \`Prisma.JsonNull\` to store the JSON null value or
         *     \`Prisma.DbNull\` to clear the JSON value and set the field to the database
         *     NULL value instead.
         */
        InputJsonValue: string | number | boolean | components["schemas"]["InputJsonObject"] | components["schemas"]["InputJsonArray"] | Record<string, never>;
        /**
         * @description Matches a JSON object.
         *     Unlike \`JsonObject\`, this type allows undefined and read-only properties.
         */
        InputJsonObject: {
            [key: string]: components["schemas"]["InputJsonValue"];
        };
        /**
         * @description Matches a JSON array.
         *     Unlike \`JsonArray\`, readonly arrays are assignable to this type.
         */
        InputJsonArray: Record<string, never>;
        CreateStandaloneTranscriptBody: {
            projectId?: string | null;
            title?: string | null;
            source?: components["schemas"]["TranscriptSource"];
            content?: string | null;
            language?: string | null;
            summary?: string | null;
            /** Format: date-time */
            recordedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
            contextIds?: string[];
            /** @enum {string} */
            persona?: "SECRETARY" | "ARCHITECT" | "PRODUCT_MANAGER" | "DEVELOPER";
            objective?: string | null;
            englishLevel?: string;
        };
        UpdateTranscriptInput: {
            title?: string | null;
            source?: components["schemas"]["TranscriptSource"];
            language?: string | null;
            summary?: string | null;
            transcript?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
            /** Format: date-time */
            recordedAt?: string | null;
        };
        "ApiResponse__success-boolean__": {
            message?: string;
            data: {
                success: boolean;
            } | null;
            /** Format: double */
            status: number;
        };
        SlideTypeConfigResponse: {
            id: string;
            templateId: string;
            slideTypeKey: string;
            displayName: string;
            description: string | null;
            parametersSchema: unknown;
            /** Format: double */
            position: number;
            /** Format: date-time */
            createdAt: string;
        };
        SlideTemplateResponse: {
            id: string;
            userId: string;
            name: string;
            description: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            backgroundColor: string | null;
            headingFont: string | null;
            bodyFont: string | null;
            logoUrl: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            slideTypes: components["schemas"]["SlideTypeConfigResponse"][];
        };
        SlideTypeConfigInput: {
            slideTypeKey: string;
            displayName: string;
            description?: string | null;
            parametersSchema: components["schemas"]["JsonValue"];
            /** Format: double */
            position?: number;
        };
        CreateTemplateRequest: {
            name: string;
            description?: string;
            primaryColor?: string;
            secondaryColor?: string;
            backgroundColor?: string;
            headingFont?: string;
            bodyFont?: string;
            logoUrl?: string;
            slideTypes?: components["schemas"]["SlideTypeConfigInput"][];
        };
        UpdateTemplateRequest: {
            name?: string;
            description?: string;
            primaryColor?: string;
            secondaryColor?: string;
            backgroundColor?: string;
            headingFont?: string;
            bodyFont?: string;
            logoUrl?: string;
            slideTypes?: components["schemas"]["SlideTypeConfigInput"][];
        };
        /** @enum {string} */
        "_36_Enums.Role": "ADMIN" | "CLIENT";
        Role: components["schemas"]["_36_Enums.Role"];
        UserResponse: {
            id: string;
            firebaseUid: string;
            email: string;
            name: string | null;
            avatarUrl: string | null;
            googleId: string | null;
            isGoogleAccount: boolean;
            role: components["schemas"]["Role"];
        };
        ApiResponse_UserResponse_: {
            message?: string;
            data: components["schemas"]["UserResponse"] | null;
            /** Format: double */
            status: number;
        };
        GenericResponse: {
            message: string;
            /** Format: double */
            status: number;
        };
        "ApiResponse__customToken-string__": {
            message?: string;
            data: {
                customToken: string;
            } | null;
            /** Format: double */
            status: number;
        };
        "DefaultSelection_Prisma._36_PresentationPayload_": {
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            status: string;
            contextIds: string[];
            slidesJson: components["schemas"]["JsonValue"];
            title: string;
            templateId: string;
            userId: string;
            id: string;
        };
        PublicPresentationResponse: {
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            status: string;
            contextIds: string[];
            slidesJson: components["schemas"]["JsonValue"];
            title: string;
            templateId: string;
            userId: string;
            id: string;
        };
        /** @enum {string} */
        "_36_Enums.ProjectStatus": "ACTIVE" | "COMPLETED" | "ARCHIVED";
        ProjectStatus: components["schemas"]["_36_Enums.ProjectStatus"];
        ProjectResponse: {
            id: string;
            title: string;
            description: string | null;
            status: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            endedAt: string | null;
            metadata: components["schemas"]["JsonValue"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectListResponse: {
            projects: components["schemas"]["ProjectResponse"][];
            /** Format: double */
            total: number;
        };
        ApiResponse_ProjectListResponse_: {
            message?: string;
            data: components["schemas"]["ProjectListResponse"] | null;
            /** Format: double */
            status: number;
        };
        TranscriptResponse: {
            id: string;
            projectId: string | null;
            userId: string;
            title: string | null;
            source: components["schemas"]["TranscriptSource"];
            language: string | null;
            summary: string | null;
            transcript: string | null;
            /** Format: date-time */
            recordedAt: string | null;
            metadata: components["schemas"]["JsonValue"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        "_36_Enums.TaskStatus": "COMPLETED" | "ARCHIVED" | "BACKLOG" | "IN_PROGRESS" | "BLOCKED";
        TaskStatus: components["schemas"]["_36_Enums.TaskStatus"];
        /** @enum {string} */
        "_36_Enums.TaskPriority": "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        TaskPriority: components["schemas"]["_36_Enums.TaskPriority"];
        TaskResponse: {
            id: string;
            projectId: string;
            title: string;
            description: string | null;
            summary: string | null;
            acceptanceCriteria: string | null;
            status: components["schemas"]["TaskStatus"];
            priority: components["schemas"]["TaskPriority"];
            /** Format: date-time */
            dueDate: string | null;
            dependencies: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TranscriptTaskInsight: {
            title: string;
            description?: string;
            priority?: components["schemas"]["TaskPriority"];
            status?: components["schemas"]["TaskStatus"];
            dueDate?: string | null;
        };
        TranscriptAnalysisResponse: {
            language: string;
            summary: string | null;
            tasks: components["schemas"]["TranscriptTaskInsight"][];
        };
        CreateTranscriptResponse: {
            transcript: components["schemas"]["TranscriptResponse"];
            tasks: components["schemas"]["TaskResponse"][];
            analysis: components["schemas"]["TranscriptAnalysisResponse"];
        };
        ApiResponse_CreateTranscriptResponse_: {
            message?: string;
            data: components["schemas"]["CreateTranscriptResponse"] | null;
            /** Format: double */
            status: number;
        };
        TranscriptListResponse: {
            transcripts: components["schemas"]["TranscriptResponse"][];
            /** Format: double */
            total: number;
        };
        ApiResponse_TranscriptListResponse_: {
            message?: string;
            data: components["schemas"]["TranscriptListResponse"] | null;
            /** Format: double */
            status: number;
        };
        ImportTranscriptRequest: {
            transcriptId: string;
            contextIds?: string[];
            /** @enum {string} */
            persona?: "SECRETARY" | "ARCHITECT" | "PRODUCT_MANAGER" | "DEVELOPER";
            objective?: string;
            englishLevel?: string;
        };
        ApiResponse_TranscriptResponse_: {
            message?: string;
            data: components["schemas"]["TranscriptResponse"] | null;
            /** Format: double */
            status: number;
        };
        ManualTranscriptRequest: {
            title?: string | null;
            source?: components["schemas"]["TranscriptSource"];
            language?: string | null;
            summary?: string | null;
            content?: string | null;
            /** Format: date-time */
            recordedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        UpdateTranscriptRequest: {
            title?: string | null;
            source?: components["schemas"]["TranscriptSource"];
            language?: string | null;
            summary?: string | null;
            transcript?: string | null;
            /** Format: date-time */
            recordedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        ApiResponse_null_: {
            message?: string;
            data: unknown;
            /** Format: double */
            status: number;
        };
        TaskListResponse: {
            tasks: components["schemas"]["TaskResponse"][];
            /** Format: double */
            total: number;
        };
        ApiResponse_TaskListResponse_: {
            message?: string;
            data: components["schemas"]["TaskListResponse"] | null;
            /** Format: double */
            status: number;
        };
        ApiResponse_TaskResponse_: {
            message?: string;
            data: components["schemas"]["TaskResponse"] | null;
            /** Format: double */
            status: number;
        };
        CreateTaskRequest: {
            title: string;
            description?: string | null;
            summary?: string | null;
            acceptanceCriteria?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /**
             * Format: date-time
             * @description Format: date-time
             */
            dueDate?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
            dependencyTaskIds?: string[];
        };
        UpdateTaskRequest: {
            title?: string;
            description?: string | null;
            summary?: string | null;
            acceptanceCriteria?: string | null;
            status?: components["schemas"]["TaskStatus"];
            priority?: components["schemas"]["TaskPriority"];
            /**
             * Format: date-time
             * @description Format: date-time
             */
            dueDate?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
            dependencyTaskIds?: string[];
        };
        ApiResponse_ProjectResponse_: {
            message?: string;
            data: components["schemas"]["ProjectResponse"] | null;
            /** Format: double */
            status: number;
        };
        CreateProjectRequest: {
            title: string;
            description?: string;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        UpdateProjectRequest: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        CreateTranscriptRequest: {
            content?: string;
            objective?: string;
            title?: string;
            source?: components["schemas"]["TranscriptSource"];
            /** Format: date-time */
            recordedAt?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
            contextIds?: string[];
            /** @enum {string} */
            persona?: "SECRETARY" | "ARCHITECT" | "PRODUCT_MANAGER" | "DEVELOPER";
            englishLevel?: string;
        };
        TemplateSubset: {
            name: string;
            description: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            backgroundColor: string | null;
            headingFont: string | null;
            bodyFont: string | null;
            logoUrl: string | null;
        };
        PresentationResponse: {
            id: string;
            userId: string;
            templateId: string;
            template?: components["schemas"]["TemplateSubset"];
            title: string;
            slidesJson: unknown;
            contextIds: string[];
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GeneratePresentationRequest: {
            templateId: string;
            contextIds: string[];
            prompt: string;
            title?: string;
            /** Format: double */
            numSlides?: number;
        };
        UpdatePresentationRequest: {
            title?: string;
            status?: string;
        };
        UpdatePresentationStatusRequest: {
            status: string;
        };
        JiraAuthorizationResponse: {
            authorizationUrl: string;
        };
        ApiResponse_JiraAuthorizationResponse_: {
            message?: string;
            data: components["schemas"]["JiraAuthorizationResponse"] | null;
            /** Format: double */
            status: number;
        };
        /** @enum {string} */
        "_36_Enums.IntegrationProvider": "JIRA" | "LINEAR";
        IntegrationProvider: components["schemas"]["_36_Enums.IntegrationProvider"];
        /** @enum {string} */
        "_36_Enums.IntegrationStatus": "CONNECTED" | "DISCONNECTED" | "ERROR";
        IntegrationStatus: components["schemas"]["_36_Enums.IntegrationStatus"];
        UserIntegrationSummary: {
            id: string;
            provider: components["schemas"]["IntegrationProvider"];
            status: components["schemas"]["IntegrationStatus"];
            accountId: string | null;
            accountName: string | null;
            metadata: components["schemas"]["JsonValue"] | null;
            scope: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            hasRefreshToken: boolean;
        };
        "ApiResponse_UserIntegrationSummary-Array_": {
            message?: string;
            data: components["schemas"]["UserIntegrationSummary"][] | null;
            /** Format: double */
            status: number;
        };
        "ApiResponse_UserIntegrationSummary-or-null_": {
            message?: string;
            data: components["schemas"]["UserIntegrationSummary"] | null;
            /** Format: double */
            status: number;
        };
        ApiResponse_string_: {
            message?: string;
            data: string | null;
            /** Format: double */
            status: number;
        };
        ContextFileResponse: {
            id: string;
            fileName: string;
            mimeType: string;
            /** Format: double */
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
            bucketPath: string;
            publicUrl: string;
        };
        ContextResponse: {
            id: string;
            name: string;
            description: string | null;
            color: string | null;
            metadata: components["schemas"]["JsonValue"] | null;
            files: components["schemas"]["ContextFileResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ContextListResponse: {
            contexts: components["schemas"]["ContextResponse"][];
        };
        ApiResponse_ContextListResponse_: {
            message?: string;
            data: components["schemas"]["ContextListResponse"] | null;
            /** Format: double */
            status: number;
        };
        ApiResponse_ContextResponse_: {
            message?: string;
            data: components["schemas"]["ContextResponse"] | null;
            /** Format: double */
            status: number;
        };
        CreateContextRequest: {
            name: string;
            description?: string | null;
            color?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        UpdateContextRequest: {
            name?: string;
            description?: string | null;
            color?: string | null;
            metadata?: components["schemas"]["InputJsonValue"] | null;
        };
        /** @enum {string} */
        "_36_Enums.ChatRole": "USER" | "ASSISTANT";
        ChatRole: components["schemas"]["_36_Enums.ChatRole"];
        ChatMessage: {
            id: string;
            threadId: string;
            role: components["schemas"]["ChatRole"];
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        ChatThread: {
            id: string;
            userId: string;
            title: string;
            contextIds: string[];
            englishLevel?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messages?: components["schemas"]["ChatMessage"][];
        };
        CreateThreadRequest: {
            title?: string;
            contextIds: string[];
            englishLevel?: string;
        };
        SendMessageResponse: {
            message: components["schemas"]["ChatMessage"];
            response: components["schemas"]["ChatMessage"];
        };
        SendMessageRequest: {
            content: string;
        };
        "ApiResponse__text-string__": {
            message?: string;
            data: {
                text: string;
            } | null;
            /** Format: double */
            status: number;
        };
        "DefaultSelection_Prisma._36_CustomThemePayload_": {
            configJson: components["schemas"]["JsonValue"];
            /** Format: double */
            density: number;
            /** Format: double */
            borderRadius: number;
            headingFontFamily: string;
            fontFamily: string;
            textSecondaryColor: string;
            textPrimaryColor: string;
            surfaceColor: string;
            backgroundColor: string;
            secondaryColor: string;
            primaryColor: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            userId: string;
            id: string;
        };
        /** @description Model CustomTheme */
        CustomTheme: components["schemas"]["DefaultSelection_Prisma._36_CustomThemePayload_"];
        "ApiResponse_CustomTheme-or-null_": {
            message?: string;
            data: components["schemas"]["CustomTheme"] | null;
            /** Format: double */
            status: number;
        };
        ApiResponse_CustomTheme_: {
            message?: string;
            data: components["schemas"]["CustomTheme"] | null;
            /** Format: double */
            status: number;
        };
        UpdateCustomThemeRequest: {
            primaryColor?: string | null;
            secondaryColor?: string | null;
            backgroundColor?: string | null;
            surfaceColor?: string | null;
            textPrimaryColor?: string | null;
            textSecondaryColor?: string | null;
            fontFamily?: string | null;
            headingFontFamily?: string | null;
            /** Format: double */
            borderRadius?: number | null;
            /** Format: double */
            density?: number | null;
            configJson?: components["schemas"]["JsonValue"] | null;
        };
        ApiResponse_boolean_: {
            message?: string;
            data: boolean | null;
            /** Format: double */
            status: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListTranscripts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                source?: components["schemas"]["TranscriptSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StandaloneTranscriptListResponse_"];
                };
            };
        };
    };
    CreateTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStandaloneTranscriptBody"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StandaloneTranscriptResponse_"];
                };
            };
        };
    };
    GetTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StandaloneTranscriptResponse_"];
                };
            };
        };
    };
    UpdateTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTranscriptInput"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StandaloneTranscriptResponse_"];
                };
            };
        };
    };
    DeleteTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse__success-boolean__"];
                };
            };
        };
    };
    ListTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideTemplateResponse"][];
                };
            };
        };
    };
    CreateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideTemplateResponse"];
                };
            };
        };
    };
    GetTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideTemplateResponse"];
                };
            };
        };
    };
    UpdateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideTemplateResponse"];
                };
            };
        };
    };
    DeleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    uuid: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserResponse_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserResponse_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    GetDesktopToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse__customToken-string__"];
                };
            };
        };
    };
    GetPublicPresentation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPresentationResponse"];
                };
            };
        };
    };
    ListSessions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: components["schemas"]["ProjectStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectListResponse_"];
                };
            };
        };
    };
    CreateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectResponse_"];
                };
            };
        };
    };
    UploadTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                    title?: string;
                    recordedAt?: string;
                    metadata?: string;
                    persona?: string;
                    objective?: string;
                    contextIds?: string;
                    englishLevel?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CreateTranscriptResponse_"];
                };
            };
        };
    };
    ListProjectTranscripts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TranscriptListResponse_"];
                };
            };
        };
    };
    CreateProjectTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTranscriptRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CreateTranscriptResponse_"];
                };
            };
        };
    };
    ImportProjectTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTranscriptRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CreateTranscriptResponse_"];
                };
            };
        };
    };
    GetProjectTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                transcriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TranscriptResponse_"];
                };
            };
        };
    };
    UpdateProjectTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                transcriptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTranscriptRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TranscriptResponse_"];
                };
            };
        };
    };
    DeleteProjectTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                transcriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_null_"];
                };
            };
        };
    };
    CreateManualTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualTranscriptRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TranscriptResponse_"];
                };
            };
        };
    };
    ListTasks: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"];
                priority?: components["schemas"]["TaskPriority"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TaskListResponse_"];
                };
            };
        };
    };
    CreateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TaskResponse_"];
                };
            };
        };
    };
    GetTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TaskResponse_"];
                };
            };
        };
    };
    UpdateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TaskResponse_"];
                };
            };
        };
    };
    DeleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_null_"];
                };
            };
        };
    };
    GetSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectResponse_"];
                };
            };
        };
    };
    UpdateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ProjectResponse_"];
                };
            };
        };
    };
    DeleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_null_"];
                };
            };
        };
    };
    GeneratePresentation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePresentationRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentationResponse"];
                };
            };
        };
    };
    ListPresentations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentationResponse"][];
                };
            };
        };
    };
    GetPresentation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentationResponse"];
                };
            };
        };
    };
    DeletePresentation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    UpdatePresentation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePresentationRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentationResponse"];
                };
            };
        };
    };
    UpdatePresentationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presentationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePresentationStatusRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresentationResponse"];
                };
            };
        };
    };
    GetAuthorizationUrl: {
        parameters: {
            query?: {
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_JiraAuthorizationResponse_"];
                };
            };
        };
    };
    HandleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
                error_description?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserIntegrationSummary-Array_"];
                };
            };
        };
    };
    GetIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_UserIntegrationSummary-or-null_"];
                };
            };
        };
    };
    GetStatusPayload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_string_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    ListContexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextListResponse_"];
                };
            };
        };
    };
    CreateContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContextRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextResponse_"];
                };
            };
        };
    };
    GetContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextResponse_"];
                };
            };
        };
    };
    UpdateContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContextRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextResponse_"];
                };
            };
        };
    };
    DeleteContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_null_"];
                };
            };
        };
    };
    GetContextFileContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: string;
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    UploadContextFile: {
        parameters: {
            query?: {
                metadata?: string;
            };
            header?: never;
            path: {
                contextId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextResponse_"];
                };
            };
        };
    };
    DeleteContextFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: string;
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ContextResponse_"];
                };
            };
        };
    };
    ListThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"][];
                };
            };
        };
    };
    CreateThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"];
                };
            };
        };
    };
    GetThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"];
                };
            };
        };
    };
    UpdateThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    englishLevel?: string;
                    contextIds?: string[];
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThread"];
                };
            };
        };
    };
    DeleteThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    SendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
        };
    };
    TranscribeChunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    mic?: string;
                    /** Format: binary */
                    system?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse__text-string__"];
                };
            };
        };
    };
    GetCustomTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CustomTheme-or-null_"];
                };
            };
        };
    };
    UpsertCustomTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomThemeRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CustomTheme_"];
                };
            };
        };
    };
    DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_boolean_"];
                };
            };
        };
    };
    DeleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_boolean_"];
                };
            };
        };
    };
}
