export interface DocThemePreset {
  name: string;
  headingFont: string;
  bodyFont: string;
  primaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
}

export const DOC_THEME_PRESETS: DocThemePreset[] = [
  {
    name: "BlueBerryBytes",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#21429c",
    accentColor: "#f87116",
    backgroundColor: "#ffffff",
    textColor: "#020817",
  },
  {
    name: "Indigo Night",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#6366f1",
    accentColor: "#a78bfa",
    backgroundColor: "#0f172a",
    textColor: "#e2e8f0",
  },
  {
    name: "Ocean Breeze",
    headingFont: "Poppins",
    bodyFont: "Inter",
    primaryColor: "#0ea5e9",
    accentColor: "#38bdf8",
    backgroundColor: "#0c1222",
    textColor: "#e0e7ff",
  },
  {
    name: "Emerald Forest",
    headingFont: "Outfit",
    bodyFont: "Source Sans 3",
    primaryColor: "#10b981",
    accentColor: "#34d399",
    backgroundColor: "#0a1a14",
    textColor: "#d1fae5",
  },
  {
    name: "Sunset Glow",
    headingFont: "Roboto",
    bodyFont: "Roboto",
    primaryColor: "#f59e0b",
    accentColor: "#fbbf24",
    backgroundColor: "#1a1008",
    textColor: "#fef3c7",
  },
  {
    name: "Rose Quartz",
    headingFont: "Playfair Display",
    bodyFont: "Lato",
    primaryColor: "#f43f5e",
    accentColor: "#fb7185",
    backgroundColor: "#1a0a10",
    textColor: "#ffe4e6",
  },
  {
    name: "Arctic Blue",
    headingFont: "Inter",
    bodyFont: "Inter",
    primaryColor: "#3b82f6",
    accentColor: "#60a5fa",
    backgroundColor: "#ffffff",
    textColor: "#1e3a8a",
  },
  {
    name: "Corporate Clean",
    headingFont: "Roboto",
    bodyFont: "Open Sans",
    primaryColor: "#1e40af",
    accentColor: "#3b82f6",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
  },
  {
    name: "Warm Earth",
    headingFont: "Merriweather",
    bodyFont: "Source Sans 3",
    primaryColor: "#d97706",
    accentColor: "#92400e",
    backgroundColor: "#fefce8",
    textColor: "#451a03",
  },
  {
    name: "Neon Cyber",
    headingFont: "Space Grotesk",
    bodyFont: "JetBrains Mono",
    primaryColor: "#06b6d4",
    accentColor: "#8b5cf6",
    backgroundColor: "#020617",
    textColor: "#cffafe",
  },
  {
    name: "Minimal Mono",
    headingFont: "DM Sans",
    bodyFont: "DM Sans",
    primaryColor: "#18181b",
    accentColor: "#71717a",
    backgroundColor: "#fafafa",
    textColor: "#27272a",
  },
  {
    name: "Lavender Mist",
    headingFont: "Nunito",
    bodyFont: "Inter",
    primaryColor: "#8b5cf6",
    accentColor: "#c4b5fd",
    backgroundColor: "#0f172a",
    textColor: "#ede9fe",
  },
  {
    name: "Midnight Crimson",
    headingFont: "Montserrat",
    bodyFont: "Open Sans",
    primaryColor: "#e11d48",
    accentColor: "#fb7185",
    backgroundColor: "#0a0a0a",
    textColor: "#ffe4e6",
  },
  {
    name: "Forest Canopy",
    headingFont: "Merriweather",
    bodyFont: "Lato",
    primaryColor: "#059669",
    accentColor: "#34d399",
    backgroundColor: "#f0fdf4",
    textColor: "#064e3b",
  },
  {
    name: "Golden Hour",
    headingFont: "Playfair Display",
    bodyFont: "Source Sans 3",
    primaryColor: "#ca8a04",
    accentColor: "#fde047",
    backgroundColor: "#292524",
    textColor: "#fef08a",
  },
  {
    name: "Cyberpunk City",
    headingFont: "Space Grotesk",
    bodyFont: "JetBrains Mono",
    primaryColor: "#d946ef",
    accentColor: "#06b6d4",
    backgroundColor: "#020617",
    textColor: "#fdf4ff",
  },
  {
    name: "Nordic Winter",
    headingFont: "Outfit",
    bodyFont: "Inter",
    primaryColor: "#0284c7",
    accentColor: "#7dd3fc",
    backgroundColor: "#1e293b",
    textColor: "#e0f2fe",
  },
  {
    name: "Vintage Sepia",
    headingFont: "Raleway",
    bodyFont: "Lato",
    primaryColor: "#92400e",
    accentColor: "#b45309",
    backgroundColor: "#fffbeb",
    textColor: "#451a03",
  },
  {
    name: "Mint Sherbet",
    headingFont: "Poppins",
    bodyFont: "Nunito",
    primaryColor: "#0d9488",
    accentColor: "#5eead4",
    backgroundColor: "#ffffff",
    textColor: "#134e4a",
  },
  {
    name: "Cosmic Void",
    headingFont: "Montserrat",
    bodyFont: "DM Sans",
    primaryColor: "#c084fc",
    accentColor: "#e879f9",
    backgroundColor: "#09090b",
    textColor: "#f3e8ff",
  },
  {
    name: "Royal Velvet",
    headingFont: "Space Grotesk",
    bodyFont: "Open Sans",
    primaryColor: "#fbbf24",
    accentColor: "#f59e0b",
    backgroundColor: "#2e1065",
    textColor: "#fcd34d",
  },
];
