ALTER TYPE "DiagramType" ADD VALUE 'STATE';
ALTER TYPE "DiagramType" ADD VALUE 'JOURNEY';
ALTER TYPE "DiagramType" ADD VALUE 'GIT';
ALTER TYPE "DiagramType" ADD VALUE 'TIMELINE';
ALTER TYPE "DiagramType" ADD VALUE 'PIE';
