/**
 * 10 curated theme presets with colors and typography pairings.
 */
export interface ThemePreset {
  name: string;
  primaryColor: string;
  secondaryColor: string;
  backgroundColor: string;
  headingFont: string;
  bodyFont: string;
  backgroundStyle: "solid" | "gradient" | "mesh" | "minimal";
  cardStyle: "flat" | "glass" | "outline";
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: "BlueBerryBytes",
    primaryColor: "#21429c",
    secondaryColor: "#f87116",
    backgroundColor: "#ffffff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Indigo Night",
    primaryColor: "#6366f1",
    secondaryColor: "#a78bfa",
    backgroundColor: "#0f172a",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Ocean Breeze",
    primaryColor: "#0ea5e9",
    secondaryColor: "#38bdf8",
    backgroundColor: "#0c1222",
    headingFont: "Poppins",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Emerald Forest",
    primaryColor: "#10b981",
    secondaryColor: "#34d399",
    backgroundColor: "#0a1a14",
    headingFont: "Outfit",
    bodyFont: "Source Sans 3",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Sunset Glow",
    primaryColor: "#f59e0b",
    secondaryColor: "#fbbf24",
    backgroundColor: "#1a1008",
    headingFont: "Roboto",
    bodyFont: "Roboto",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Rose Quartz",
    primaryColor: "#f43f5e",
    secondaryColor: "#fb7185",
    backgroundColor: "#1a0a10",
    headingFont: "Playfair Display",
    bodyFont: "Lato",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Arctic Blue",
    primaryColor: "#3b82f6",
    secondaryColor: "#60a5fa",
    backgroundColor: "#ffffff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Corporate Clean",
    primaryColor: "#1e40af",
    secondaryColor: "#3b82f6",
    backgroundColor: "#f8fafc",
    headingFont: "Roboto",
    bodyFont: "Open Sans",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Warm Earth",
    primaryColor: "#d97706",
    secondaryColor: "#92400e",
    backgroundColor: "#fefce8",
    headingFont: "Merriweather",
    bodyFont: "Source Sans 3",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Neon Cyber",
    primaryColor: "#06b6d4",
    secondaryColor: "#8b5cf6",
    backgroundColor: "#020617",
    headingFont: "Space Grotesk",
    bodyFont: "JetBrains Mono",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Minimal Mono",
    primaryColor: "#18181b",
    secondaryColor: "#71717a",
    backgroundColor: "#fafafa",
    headingFont: "DM Sans",
    bodyFont: "DM Sans",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Lavender Mist",
    primaryColor: "#8b5cf6",
    secondaryColor: "#c4b5fd",
    backgroundColor: "#0f172a",
    headingFont: "Nunito",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Midnight Crimson",
    primaryColor: "#e11d48",
    secondaryColor: "#fb7185",
    backgroundColor: "#0a0a0a",
    headingFont: "Montserrat",
    bodyFont: "Open Sans",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Forest Canopy",
    primaryColor: "#059669",
    secondaryColor: "#34d399",
    backgroundColor: "#f0fdf4",
    headingFont: "Merriweather",
    bodyFont: "Lato",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Golden Hour",
    primaryColor: "#ca8a04",
    secondaryColor: "#fde047",
    backgroundColor: "#292524",
    headingFont: "Playfair Display",
    bodyFont: "Source Sans 3",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Cyberpunk City",
    primaryColor: "#d946ef",
    secondaryColor: "#06b6d4",
    backgroundColor: "#020617",
    headingFont: "Space Grotesk",
    bodyFont: "JetBrains Mono",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Nordic Winter",
    primaryColor: "#0284c7",
    secondaryColor: "#7dd3fc",
    backgroundColor: "#1e293b",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Vintage Sepia",
    primaryColor: "#92400e",
    secondaryColor: "#b45309",
    backgroundColor: "#fffbeb",
    headingFont: "Raleway",
    bodyFont: "Lato",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Mint Sherbet",
    primaryColor: "#0d9488",
    secondaryColor: "#5eead4",
    backgroundColor: "#ffffff",
    headingFont: "Poppins",
    bodyFont: "Nunito",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Cosmic Void",
    primaryColor: "#c084fc",
    secondaryColor: "#e879f9",
    backgroundColor: "#09090b",
    headingFont: "Montserrat",
    bodyFont: "DM Sans",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Royal Velvet",
    primaryColor: "#fbbf24",
    secondaryColor: "#f59e0b",
    backgroundColor: "#2e1065",
    headingFont: "Space Grotesk",
    bodyFont: "Open Sans",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Golden Hour",
    primaryColor: "#d97706",
    secondaryColor: "#fbbf24",
    backgroundColor: "#fffbeb",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Midnight Purple",
    primaryColor: "#c084fc",
    secondaryColor: "#e879f9",
    backgroundColor: "#1e1b4b",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Cyber Punk",
    primaryColor: "#f43f5e",
    secondaryColor: "#0ea5e9",
    backgroundColor: "#000000",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Slate Professional",
    primaryColor: "#475569",
    secondaryColor: "#94a3b8",
    backgroundColor: "#f8fafc",
    headingFont: "Roboto",
    bodyFont: "Roboto",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Lavender Dream",
    primaryColor: "#8b5cf6",
    secondaryColor: "#a78bfa",
    backgroundColor: "#f5f3ff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Corporate Blue",
    primaryColor: "#2563eb",
    secondaryColor: "#60a5fa",
    backgroundColor: "#ffffff",
    headingFont: "Roboto",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Neon Nights",
    primaryColor: "#ff007f",
    secondaryColor: "#7f00ff",
    backgroundColor: "#0f0f0f",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Soft Peach",
    primaryColor: "#f472b6",
    secondaryColor: "#fb7185",
    backgroundColor: "#fff1f2",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Crimson Dark",
    primaryColor: "#dc2626",
    secondaryColor: "#ef4444",
    backgroundColor: "#171717",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Mint Fresh",
    primaryColor: "#10b981",
    secondaryColor: "#059669",
    backgroundColor: "#ecfdf5",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Coffee Roast",
    primaryColor: "#b45309",
    secondaryColor: "#d97706",
    backgroundColor: "#fffbeb",
    headingFont: "Merriweather",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Arctic Blue",
    primaryColor: "#38bdf8",
    secondaryColor: "#7dd3fc",
    backgroundColor: "#f0f9ff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Electric Violet",
    primaryColor: "#7c3aed",
    secondaryColor: "#a78bfa",
    backgroundColor: "#1c192b",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Lemon Chiffon",
    primaryColor: "#eab308",
    secondaryColor: "#fde047",
    backgroundColor: "#fefce8",
    headingFont: "Roboto",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Obsidian",
    primaryColor: "#3b82f6",
    secondaryColor: "#60a5fa",
    backgroundColor: "#050505",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Ruby Rose",
    primaryColor: "#e11d48",
    secondaryColor: "#fb7185",
    backgroundColor: "#fff1f2",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Teal Oceans",
    primaryColor: "#0f766e",
    secondaryColor: "#14b8a6",
    backgroundColor: "#f0fdfa",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Deep Space",
    primaryColor: "#a855f7",
    secondaryColor: "#d8b4fe",
    backgroundColor: "#09090b",
    headingFont: "Roboto",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Mustard Seed",
    primaryColor: "#ca8a04",
    secondaryColor: "#facc15",
    backgroundColor: "#fdfce8",
    headingFont: "Merriweather",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Autumn Leaves",
    primaryColor: "#ea580c",
    secondaryColor: "#fb923c",
    backgroundColor: "#fff7ed",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Charcoal Minimal",
    primaryColor: "#171717",
    secondaryColor: "#404040",
    backgroundColor: "#ffffff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Berry Smoothie",
    primaryColor: "#9d174d",
    secondaryColor: "#f472b6",
    backgroundColor: "#fdf2f8",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Nordic Minimal",
    primaryColor: "#334155",
    secondaryColor: "#64748b",
    backgroundColor: "#f8fafc",
    headingFont: "Inter",
    bodyFont: "Roboto",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Neon Green",
    primaryColor: "#16a34a",
    secondaryColor: "#4ade80",
    backgroundColor: "#022c22",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Sunset Orange",
    primaryColor: "#f97316",
    secondaryColor: "#fdba74",
    backgroundColor: "#1f140e",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Cool Gray",
    primaryColor: "#6b7280",
    secondaryColor: "#9ca3af",
    backgroundColor: "#f9fafb",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Warm Bronze",
    primaryColor: "#b45309",
    secondaryColor: "#f59e0b",
    backgroundColor: "#2e1c0d",
    headingFont: "Merriweather",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Sky Cloud",
    primaryColor: "#0284c7",
    secondaryColor: "#38bdf8",
    backgroundColor: "#ffffff",
    headingFont: "Inter",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Plum Deep",
    primaryColor: "#86198f",
    secondaryColor: "#c026d3",
    backgroundColor: "#fdf4ff",
    headingFont: "Outfit",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
  {
    name: "Tech Blue",
    primaryColor: "#0070f3",
    secondaryColor: "#3291ff",
    backgroundColor: "#000000",
    headingFont: "Roboto",
    bodyFont: "Inter",
    backgroundStyle: "solid",
    cardStyle: "flat",
  },
];

export const FONT_OPTIONS: string[] = [
  "Inter",
  "Roboto",
  "Poppins",
  "Open Sans",
  "Lato",
  "Outfit",
  "DM Sans",
  "Source Sans 3",
  "Playfair Display",
  "Merriweather",
  "Space Grotesk",
  "JetBrains Mono",
  "Montserrat",
  "Nunito",
  "Raleway",
];
